// Code generated by server_generator. DO NOT EDIT.
// generated version: 0.4.0

package room

import (
	"net/http"

	"github.com/labstack/echo/v4"

	props "github.com/go-generalize/api_gen/server_generator/sample2/props"
)

type Routes struct {
	router *echo.Group
}

func NewRoutes(p *props.ControllerProps, router *echo.Group) *Routes {
	r := &Routes{
		router: router,
	}

	router.GET("room", r.GetRoom(p))

	return r
}

func (r *Routes) GetRoom(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetRoomController(p)
	return func(c echo.Context) error {
		req := new(GetRoomRequest)
		if err := c.Bind(req); err != nil {
			return c.JSON(http.StatusBadRequest, map[string]interface{}{
				"code":    http.StatusBadRequest,
				"message": "invalid request.",
			})
		}
		res, err := i.GetRoom(c, req)
		if err != nil {
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

type IGetRoomController interface {
	GetRoom(c echo.Context, req *GetRoomRequest) (res *GetRoomResponse, err error)
}
