// Code generated by server_generator. DO NOT EDIT.
// generated version: devel

package room

import (
	"io"
	"log"
	"net/http"

	"github.com/go-generalize/api_gen/server_generator/sample2/props"
	"github.com/go-generalize/api_gen/server_generator/sample2/wrapper"
	"github.com/labstack/echo/v4"
)

// Routes ...
type Routes struct {
	router *echo.Group
}

// NewRoutes ...
func NewRoutes(p *props.ControllerProps, router *echo.Group, opts ...io.Writer) *Routes {
	if len(opts) > 0 {
		if w := opts[0]; w != nil {
			log.SetOutput(w)
		}
	}
	r := &Routes{
		router: router,
	}
	router.GET(":roomID", r.GetRoom(p))
	return r
}

// GetRoom ...
func (r *Routes) GetRoom(p *props.ControllerProps) echo.HandlerFunc {
	i := NewGetRoomController(p)

	b, ok := (interface{})(i).(interface{ AutoBind() bool })
	bindable := !ok || b.AutoBind()

	return func(c echo.Context) error {
		var req *GetRoomRequest

		if bindable {
			req = new(GetRoomRequest)
			if err := c.Bind(req); err != nil {
				log.Printf("failed to JSON binding(/api/event/{eventID}/room/{roomID}): %+v", err)
				return c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
		}
		res, err := i.GetRoom(c, req)
		if err != nil {
			if werr, ok := err.(*wrapper.APIError); ok {
				log.Printf("%+v", werr)
				return c.JSON(werr.Status, werr.Body)
			}
			return err
		}
		if res == nil {
			return nil
		}

		return c.JSON(http.StatusOK, res)
	}
}

// IGetRoomController ...
type IGetRoomController interface {
	GetRoom(c echo.Context, req *GetRoomRequest) (res *GetRoomResponse, err error)
}
