// Code generated by api_gen. DO NOT EDIT.
// Package types Don't fix this code by your own hands.
// generated version: (devel)

package types

type GetStaticPageRequest struct {
}

type GetStaticPageResponse struct {
	Body  string `json:"body"`
	Title string `json:"title"`
}
