//go:build !mock
// +build !mock

// Code generated by api_gen. DO NOT EDIT.
// generated version: devel
package server

import (
	"net/http"

	types_interfaces_21ff36cc "github.com/go-generalize/api_gen/v2/pkg/server/tmp/alias_repro/interfaces"
	ctrl_controller_b7c4244f "github.com/go-generalize/api_gen/v2/pkg/server/tmp/alias_repro/server/controller"
	apierror "github.com/go-generalize/api_gen/v2/pkg/server/tmp/alias_repro/server/pkg/apierror"
	props "github.com/go-generalize/api_gen/v2/pkg/server/tmp/alias_repro/server/props"
	echo "github.com/labstack/echo/v4"
	xerrors "golang.org/x/xerrors"
)

func addRoutes(e *echo.Echo, p *props.ControllerProps, opt *options) {
	add := func(method, path string, handler func(c echo.Context) (interface{}, error)) {
		e.Add(method, path, func(c echo.Context) error {
			var werr *apierror.APIError

			res, err := handler(c)

			if err != nil {
				if !opt.disableErrorHandling && xerrors.As(err, &werr) {
					c.Logger().Errorf("%+v", werr)
					return c.JSON(werr.Status, werr.Body)
				}
				return xerrors.Errorf("%s %s returned an error: %w", method, path, err)
			}
			if res == nil {
				return nil
			}

			return c.JSON(http.StatusOK, res)
		})
	}

	{
		ctrl := ctrl_controller_b7c4244f.NewGetController(p)

		add("GET", "/", func(c echo.Context) (interface{}, error) {
			req := new(types_interfaces_21ff36cc.GetRequest)
			if err := c.Bind(req); err != nil {
				c.Logger().Errorf("failed to bind a request for (/): %+v", err)
				return nil, c.JSON(http.StatusBadRequest, map[string]interface{}{
					"code":    http.StatusBadRequest,
					"message": "invalid request.",
				})
			}
			if err := c.Validate(req); err != nil && err != echo.ErrValidatorNotRegistered {
				return nil, xerrors.Errorf("the validator returned an error: %w", err)
			}

			res, err := ctrl.Get(c, req)

			if err != nil {
				return nil, xerrors.Errorf("the handler(Get) returned an error: %w", err)
			}

			if res == nil {
				return nil, nil
			}

			return res, nil
		})
	}

}
