// Code generated by api_gen. DO NOT EDIT.
// Package types Don't fix this code by your own hands.
// generated version: (devel)

package types

import (
	"time"
)

type GetRequest struct {
}

type GetResponse struct {
}

type PostUpdateUserNameRequest struct {
	Name string
}

type PostUpdateUserNameResponse struct {
	Message     string
	RequestTime time.Time
	Status      bool
}

type PostUpdateUserPasswordRequest struct {
	Password        string
	PasswordConfirm string
}

type PostUpdateUserPasswordResponse struct {
	Message     string
	RequestTime time.Time
	Status      bool
}
