// Code generated by api_gen. DO NOT EDIT.
// Package types Don't fix this code by your own hands.
// generated version: (devel)

package types

import (
	"time"
)

type GetArticleRequest struct {
	ID int
}

type GetArticleResponse struct {
	Body        string
	Group       []string
	ID          int
	RequestTime time.Time
}
