// Code generated by api_gen. DO NOT EDIT.
// Package types Don't fix this code by your own hands.
// generated version: (devel)

package types

import (
	"time"
)

type Company struct {
	Metadata Metadata
}

type Department struct {
	Metadata Metadata
}

type GetGroupsRequest struct {
}

type GetGroupsResponse struct {
	Companies   []Company
	Departments []Department
}

type Metadata struct {
	CreatedAt time.Time
	DeletedAt *time.Time
	ID        string
	Name      string
	UpdatedAt time.Time
}
