// Code generated by api_gen. DO NOT EDIT.
// Package types Don't fix this code by your own hands.
// generated version: (devel)

package types

import (
	"time"
)

type GetUserJobGetRequest struct {
	UserID string `param:"userID"`
}

type GetUserJobGetResponse struct {
	JobName     string
	RequestTime time.Time
}
