// Code generated by server_generator. DO NOT EDIT.
// generated version: unknown

// Package main is a mock server
package main

import (
	"flag"
	"fmt"
	"log"

	"github.com/go-generalize/api_gen/templates/backend/interfaces"
	"github.com/go-generalize/api_gen/templates/backend/interfaces/props"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

func main() {
	port := flag.Int("port", 15000, "mock server listen port")
	flag.Parse()

	p := &props.ControllerProps{}
	e := echo.New()
	m := interfaces.MiddlewareList{}

	e.Use(middleware.Recover())
	e.Use(middleware.CORS())

	interfaces.Bootstrap(p, e, m)

	fmt.Println("All routes are...")
	for _, r := range e.Routes() {
		fmt.Printf("%s %s: %s\n", r.Method, r.Path, r.Name)
	}

	l := fmt.Sprintf(":%d", *port)
	log.Fatal(e.Start(l))
}
