// Code generated by api_gen. DO NOT EDIT.
// Package types Don't fix this code by your own hands.
// generated version: (devel)

package types

import (
	"time"
)

type PutJobRequest struct {
	JobID  string
	UserID string `param:"userID"`
}

type PutJobResponse struct {
	JobID       string
	RequestTime time.Time
	UserID      string
}
