project_name: client_generator
env:
  - GO111MODULE=on
builds:
  - main: .
    binary: client_generator
    ldflags:
      - -s -w
      - -X github.com/go-generalize/api_gen/common.AppVersion={{.Version}}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
