// Code generated by api_gen. DO NOT EDIT.
// Package types Don't fix this code by your own hands.
// generated version: (devel)

package types

type PostUserRequest struct {
}

type PostUserResponse struct {
}
